// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeRL1sDLZnNd8pfBVJWFabCDZcNkv5YfI',
    appId: '1:770487677240:web:a4ad9b452b4a15890451cd',
    messagingSenderId: '770487677240',
    projectId: 'new-sajilo-yatayat',
    authDomain: 'new-sajilo-yatayat.firebaseapp.com',
    storageBucket: 'new-sajilo-yatayat.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPRHJ-iurvJgMZu-cdosKdFTMZDO7hD3Y',
    appId: '1:770487677240:android:833a55458f38ac540451cd',
    messagingSenderId: '770487677240',
    projectId: 'new-sajilo-yatayat',
    storageBucket: 'new-sajilo-yatayat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbJm7z4wCYeqUZv4hkfQMMkSD6DHIbUVE',
    appId: '1:770487677240:ios:a0014ae5c36c3f120451cd',
    messagingSenderId: '770487677240',
    projectId: 'new-sajilo-yatayat',
    storageBucket: 'new-sajilo-yatayat.appspot.com',
    iosBundleId: 'com.example.tryapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbJm7z4wCYeqUZv4hkfQMMkSD6DHIbUVE',
    appId: '1:770487677240:ios:ed50fcea3ceaab5f0451cd',
    messagingSenderId: '770487677240',
    projectId: 'new-sajilo-yatayat',
    storageBucket: 'new-sajilo-yatayat.appspot.com',
    iosBundleId: 'com.example.tryapp.RunnerTests',
  );
}
