// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjeYg5u6exU2OUqnb3RUwiH1g9OwKKP9M',
    appId: '1:580212007323:web:3429b7341e7a45e8b0813e',
    messagingSenderId: '580212007323',
    projectId: 'sajilo-yatayat-248b4',
    authDomain: 'sajilo-yatayat-248b4.firebaseapp.com',
    storageBucket: 'sajilo-yatayat-248b4.appspot.com',
    measurementId: 'G-V0JZKRYLQL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFNZ3rtfItJgV7f-g-mwqXrFIRuaDXq9M',
    appId: '1:580212007323:android:3e73563ac5f397d6b0813e',
    messagingSenderId: '580212007323',
    projectId: 'sajilo-yatayat-248b4',
    storageBucket: 'sajilo-yatayat-248b4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKNJ0bs5N-qR3GcI3i3YSdoL0zsMcnW6k',
    appId: '1:580212007323:ios:3408c4f8ee5ab066b0813e',
    messagingSenderId: '580212007323',
    projectId: 'sajilo-yatayat-248b4',
    storageBucket: 'sajilo-yatayat-248b4.appspot.com',
    iosBundleId: 'com.example.tryapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKNJ0bs5N-qR3GcI3i3YSdoL0zsMcnW6k',
    appId: '1:580212007323:ios:014c744363306081b0813e',
    messagingSenderId: '580212007323',
    projectId: 'sajilo-yatayat-248b4',
    storageBucket: 'sajilo-yatayat-248b4.appspot.com',
    iosBundleId: 'com.example.tryapp.RunnerTests',
  );
}
